### ISSUE TITLE
Facebook SDK incompatibility with ANDROID_SUPPORT_VERSION 26+ in 2.6.1 Release

### ISSUE THREAD

**Issue by wpinaud** [OneSignal/OneSignal-Unity-SDK#88]
Hi,

As mentioned in the troubleshooting section the Facebook SDK doesn't work well with the latest of OneSignal 2.6.1 Release  out of the box.

Following this tutorial (with ANDROID_SUPPORT_VERSION 25+) : https://documentation.onesignal.com/docs/troubleshooting-unity#section-build-error-with-facebook-sdk

Fixes the Facebook issue but introduce an issue with OneSignal, the client can't subscribe to notification due to the outdated Android Support Libraries:
![https://cl.ly/pqQz/download/Image%202018-02-28%20at%209.27.55%20AM.png](https://cl.ly/pqQz/download/Image%202018-02-28%20at%209.27.55%20AM.png)

I tried to set the ANDROID_SUPPORT_VERSION to 26+, it fixes OneSignal errors but get Facebook to crash as usual 
`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleOwner;`

**Comment by Nightsd01** [comment]
@jkasten2 Any idea what would cause clients to be unable to subscribe on an older android support version?

**Comment by wpinaud** [comment]
It looks like your backend is blacklisting users with android support <26

**Comment by Nightsd01** [comment]
@wpinaud Can you send me a screenshot of your unity android Player settings?

**Comment by wpinaud** [comment]
Sure
The android player settings:
![https://cl.ly/pyFN/Image%202018-03-05%20at%209.50.19%20PM.png](https://cl.ly/pyFN/Image%202018-03-05%20at%209.50.19%20PM.png)
The OneSignal configuration:
![https://cl.ly/pxRA/Image%202018-03-05%20at%209.50.29%20PM.png](https://cl.ly/pxRA/Image%202018-03-05%20at%209.50.29%20PM.png)

I'm going to run more testing and come back to you - we have an automation plan which might modify the values at build time.

**Comment by Nightsd01** [comment]
@wpinaud Any update on what happened?

**Comment by wpinaud** [comment]
Yes, our build system replaced this value by Highest version available, and my system was setup with the SDK 27.
Removing this script and forcing unity to use SDK 25 solved the problem.

Thank you for your help and pointing me to the right direction.
