### PR TITLE
[FIX] Java Collection type parameters for Android

### PR DESCRIPTION
**Pull request by shepherd-l**
# Description
## One Line Summary
Fixes Android `DeleteTags` and `RemoveTriggers` calls to correctly use a Java array list instead of an array.

### Motivation
Fixes `JNI: Unknown signature` and `java.lang.NoSuchMethodError` errors from calling `DeleteTags` and `RemoveTriggers`.

# Testing
## Manual testing
Tested deleting tags and removing triggers on an app build with Unity 2021.3.2f1 of the Unity Example App on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/526)

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-unity-sdk/526#-:-N8S3aPX1yLBArUERR-o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brismithers)
