### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shefich** [OneSignal/OneSignal-Unity-SDK#574]
### What happened?

After update to the SDK 3.0.8 from 3.0.7 I can't make a build.

### Steps to reproduce?

```Markdown
1. Install SDK 3.0.7
2. Update to the 3.0.8
```

### What did you expect to happen?

I expected the build

### Unity version

2020.3.43

### OneSignal Unity SDK version

[3.0.8 Release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.8)

### Platform

Android

### Relevant log output

```Shell
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:30: error: cannot find symbol
public final class UnityIAMLifecycleHandler extends OSInAppMessageLifecycleHandler {
                                                    ^
  symbol: class OSInAppMessageLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:45: error: cannot find symbol
    public void onWillDisplayInAppMessage(OSInAppMessage message) {
                                          ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:51: error: cannot find symbol
    public void onDidDisplayInAppMessage(OSInAppMessage message) {
                                         ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:57: error: cannot find symbol
    public void onWillDismissInAppMessage(OSInAppMessage message) {
                                          ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:63: error: cannot find symbol
    public void onDidDismissInAppMessage(OSInAppMessage message) {
                                         ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:38: error: cannot find symbol
        void onWillDisplayInAppMessage(OSInAppMessage message);
                                       ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:39: error: cannot find symbol
        void onDidDisplayInAppMessage(OSInAppMessage message);
                                      ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:40: error: cannot find symbol
        void onWillDismissInAppMessage(OSInAppMessage message);
                                       ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:41: error: cannot find symbol
        void onDidDismissInAppMessage(OSInAppMessage message);
                                      ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:44: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:50: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:56: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\UnityProjects\xxx\Temp\gradleOut\unityLibrary\src\main\java\com\onesignal\UnityIAMLifecycleHandler.java:62: error: method does not override or implement a method from a supertype
    @Override
    ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jp-gmr** [comment]
This also happens with 3.0.7.
This is the same issue reported here:
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/573

**Comment by jkasten2** [comment]
Closing as a duplicate of #573, please follow up there.
