### PR TITLE
[Fix] Mac Catalyst build errors

### PR DESCRIPTION
**Pull request by shepherd-l**
# Description
## One Line Summary
Fixes Mac Catalyst build errors: `Use of undeclared identifier 'OneSignalLiveActivitiesManagerImpl'`

### Motivation
Fixes Mac Catalyst build errors with `OneSignalLiveActivitiesManagerImpl`. The `OneSignalLiveActivitiesManagerImpl` module uses `ActivityKit` which is not available for Mac Catalyst and causes build errors.

### Scope
Fixes live activity build errors for Mac Catalyst builds. However, Unity does not support Mac Catalyst builds either, producing build errors: `Undefined symbol _Unity...`. This PR removes the build errors from OneSignal LiveActivities though.

# Testing
## Manual testing
Tested building for Mac Catalyst, app build with Unity 2022.3.10f1 of the OneSignal example app on a physical iPhone 12 with iOS 17.5.1.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Unity-SDK/742)

### CODE REVIEW

**Comment by jkasten2** [comment]
> However, Unity does not support Mac Catalyst builds either

Sounds like we don't actually need this PR then
Sounds like we don't actually need this PR then

**Comment by shepherd-l** [comment]
I was thinking that too but it does remove the build error log pointing towards OneSignal though. And then devs who try building for Mac Catalyst can see that Unity doesn't support it for themselves

**Comment by jkasten2** [comment]
I see, ya it would be good to not have OneSignal in the build errors if they attempt that, which would be misleading of the real problem.

**Review by jkasten2 — APPROVED** [review]
